# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"(\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\"\'\n\x0fRegisterRequest\x12\x14\n\x0c\x64isplay_name\x18\x01 \x01(\t\"#\n\x10RegisterResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"#\n\x12SearchUsersRequest\x12\r\n\x05query\x18\x01 \x01(\t\"0\n\x13SearchUsersResponse\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.chat.User\"\x9c\x01\n\x0c\x43hatEnvelope\x12\x1d\n\x04type\x18\x01 \x01(\x0e\x32\x0f.chat.EventType\x12\x14\n\x0c\x66rom_user_id\x18\x02 \x01(\t\x12\x12\n\nto_user_id\x18\x03 \x01(\t\x12\x10\n\x08group_id\x18\x04 \x01(\t\x12\x12\n\nmessage_id\x18\x05 \x01(\t\x12\x0c\n\x04text\x18\x06 \x01(\t\x12\x0f\n\x07sent_ts\x18\x07 \x01(\x03*J\n\tEventType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SEND_DM\x10\x01\x12\x0e\n\nSEND_GROUP\x10\x02\x12\n\n\x06SYSTEM\x10\x03\x12\x07\n\x03\x41\x43K\x10\x04\x32\xca\x01\n\x0b\x43hatService\x12=\n\x0cRegisterUser\x12\x15.chat.RegisterRequest\x1a\x16.chat.RegisterResponse\x12\x42\n\x0bSearchUsers\x12\x18.chat.SearchUsersRequest\x1a\x19.chat.SearchUsersResponse\x12\x38\n\nOpenStream\x12\x12.chat.ChatEnvelope\x1a\x12.chat.ChatEnvelope(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTTYPE']._serialized_start=386
  _globals['_EVENTTYPE']._serialized_end=460
  _globals['_USER']._serialized_start=20
  _globals['_USER']._serialized_end=60
  _globals['_REGISTERREQUEST']._serialized_start=62
  _globals['_REGISTERREQUEST']._serialized_end=101
  _globals['_REGISTERRESPONSE']._serialized_start=103
  _globals['_REGISTERRESPONSE']._serialized_end=138
  _globals['_SEARCHUSERSREQUEST']._serialized_start=140
  _globals['_SEARCHUSERSREQUEST']._serialized_end=175
  _globals['_SEARCHUSERSRESPONSE']._serialized_start=177
  _globals['_SEARCHUSERSRESPONSE']._serialized_end=225
  _globals['_CHATENVELOPE']._serialized_start=228
  _globals['_CHATENVELOPE']._serialized_end=384
  _globals['_CHATSERVICE']._serialized_start=463
  _globals['_CHATSERVICE']._serialized_end=665
# @@protoc_insertion_point(module_scope)
